### ISSUE TITLE
First impression 

### ISSUE THREAD

**Issue by kkharji** [dosimple/workspace.vim#1] opened 2020-10-10 15:10 UTC
Hey @dosimple, I finely got the chance to try out the plugin, and I got to say its what I exactly was looking for. It worked out of the box, and to my complete surprise it integrated very well with @akinsho 's awesome bufferline plugin 'nvim-bufferline.lua'. 

Here's some feedback as requested :

- Wsc command 
   - requires a workspace number to be given. Giving the current workspace number doesn't close it.  Buffers from workspace get merged the previous workspace buffer, like close command.
   - A more desirable behavior would be: calling Wsc without arguments close current workspace. Upon closing workspaces, its buffers should be deleted as well and not merged like with close command.

- Wsmv command
   - Sometime doesn't work. I hounestly don't think I would use it a lot, but It would be more useful if an actual name could be given, like Project X

- WS command
   - Is an awesome way of navigating multiple tabs or workspace. Switching to nonexistent workspace creates new workspace in 1 and pushes the rest down the stack. for example if 1 2 are available calling WS 3 pushes 1 to be 2 and 2 to be 3 and the new one to be 1.
    - A more desirable behavior would be: reverse the behavior of creating new workspace, so the new ones get appended.

- Other
   - When there is only one buffer in a workspace, deleting the buffer `bd` doesn't close the workspace. A more desirable behavior is to delete the workspace if no buffer in it.
   - if a file is opened in ws 1 and then reopend in ws 2, the buffer get deleted from ws 1 list. A more desirable behavior is to have both buffer visible in both places.
   - creating a workspace with WS breaks when opening a buffer with fuzzy search as opposed to using the built in tabnew

Hope this feedback is useful, Thanks @dosimple .

**Comment by dosimple** [comment] 2020-10-15 14:38
Hi @tami5, thank you for your feedback.

For closing current workspace, one can use `:tabclose`. Deleting buffers upon closing workspace is an idea I've initially considered, but decided not to implement. I don't want to deviate from vim's tabpage behavior as much as possible.

For `WSmv` not working: it would be nice to know, how we reproduce it.

The behavior of `WS` you describe sounds like a bug. The intended behavior is the one you described as desirable. So I will look in to it. Could you enumerate the exact steps, how you reproduce this bug?

Closing workspace upon deleting buffers is a feature I have planned to do - nice catch.

Having a buffer in multiple workspaces: do you have an (strong) use case for it?

The last point sounds also like a bug, could you describe, how it breaks?

Also, it would be nice, if people would report each item as separate issue.

The feedback was helpful. Thanks again.

**Comment by ahmadie** [comment] 2020-10-29 15:59
Please add moving buffer from tab 1 to tab 2 PLEEAASE similar to i3 move current container to workspace 1

**Comment by dosimple** [comment] 2020-11-04 13:12
Hi, so the first point is fixed. And closing workspace upon deleting buffers is addressed by not showing empty workspaces in the info message - currently it is safer that way.

**Comment by dosimple** [comment] 2020-11-24 12:59
Ok, we are closing empty workspaces for real now - it is implemented. For moving buffers, use `WSbmv n`. For the other points, please create new issues.

**Closed as completed by dosimple** 2020-11-24 12:59 UTC

**Comment by kkharji** [comment] 2020-11-24 13:24
@dosimple thanks a lot
