### ISSUE TITLE
Problems with Sessions

### ISSUE THREAD

**Issue by pedro757** [dosimple/workspace.vim#8] opened 2021-03-22 19:19 UTC
It does not work with vim sessions

when i enter with vim -S throws this error
![image](https://user-images.githubusercontent.com/30637426/112046756-d1cdb380-8b22-11eb-9c53-7d6318f659f2.png)

**Comment by dosimple** [comment] 2021-06-29 10:22
I made some updates unrelated to session. With the latest changes, I was unable to reproduce this problem (Neovim 0.4.4).

* Could you update, test and report here again?
* Which version of Vim or Neovim are you using?
* Do you have 'sessionoptions' option changed from the default?

**Comment by pedro757** [comment] 2021-07-06 01:40
I stopped using this plugin for a while, now here's the thing, that error doesn't appear anymore but sessions does not works yet.

#### Useful information:
**Neovim version:**  v0.6.0-dev+8-g75f758b99
**sessionoptions:**  blank,buffers,curdir,folds,help,tabpages,winsize (this is the default value)

#### Steps to reproduce:
1. Open vim in `X-Folder`  
2. Create a new tab with `:tabnew Y-Folder`
3. Make a Session with `:mks`

#### Errors
1. When I close vim with `:qa` and then open with `nvim -S` to restore the session, the plugin only restores the buffers but it doesn't recover the tabs. I mean, it open all buffers from all tabs but does not recover tabs

2. When I close a buffer with `:bd` it closes the buffer and the **current tab**. (This problem is **unrelated** to sessions)

There are some guys that forked this plugin and apparently solve some of these problems but when I use those plugins, they are full of errors, and the projects seem unmaintained, but maybe those could be [useful.](https://github.com/dosimple/workspace.vim/network/members)

**Comment by dosimple** [comment] 2022-09-08 14:55
Thank you for the detailed responce. Sorry for the delay on my part.

1. Session loading was broken/unimplemented - now fixed.  Note: `globals` needs to be added to `sessionoptions`.

2. This is default vim behaviour. To avoid losing tab or window, I have been using `bbye.vim` plugin. Now we have the `:WSbrm` command for this.

**Closed as completed by dosimple** 2022-09-08 14:55 UTC
